/**
 * Compatibility entrypoint. The 2026 PTCE bank is generated by
 * scripts/generate_ptce_bank.py (unique scenario-style items).
 */
import { spawnSync } from "child_process";
import path from "path";

const script = path.join(process.cwd(), "scripts", "generate_ptce_bank.py");
const result = spawnSync("python3", [script], { stdio: "inherit" });
process.exit(result.status ?? 1);
