import * as fs from "fs";
import * as path from "path";

type DrugCategory =
  | "Cardiovascular"
  | "Diabetes"
  | "Pain & Inflammation"
  | "Mental Health"
  | "Respiratory"
  | "Antibiotic"
  | "GI"
  | "Thyroid & Hormone"
  | "Dermatology"
  | "Other";

interface TopDrug {
  id: string;
  generic: string;
  brand: string;
  drugClass: string;
  category: DrugCategory;
  indication: string;
  ptceTip: string;
}

const DRUGS: Omit<TopDrug, "id">[] = [
  { generic: "lisinopril", brand: "Prinivil/Zestril", drugClass: "ACE inhibitor", category: "Cardiovascular", indication: "Hypertension, heart failure", ptceTip: "ACE inhibitors often cause dry cough." },
  { generic: "amlodipine", brand: "Norvasc", drugClass: "Calcium channel blocker", category: "Cardiovascular", indication: "Hypertension, angina", ptceTip: "Common side effect: peripheral edema." },
  { generic: "metoprolol", brand: "Lopressor/Toprol XL", drugClass: "Beta blocker", category: "Cardiovascular", indication: "Hypertension, angina, heart failure", ptceTip: "Do not stop abruptly." },
  { generic: "atorvastatin", brand: "Lipitor", drugClass: "Statin", category: "Cardiovascular", indication: "Hyperlipidemia", ptceTip: "Take in evening for some statins; watch for myalgia." },
  { generic: "losartan", brand: "Cozaar", drugClass: "ARB", category: "Cardiovascular", indication: "Hypertension", ptceTip: "ARB alternative when ACE cough occurs." },
  { generic: "hydrochlorothiazide", brand: "Microzide", drugClass: "Thiazide diuretic", category: "Cardiovascular", indication: "Hypertension, edema", ptceTip: "Monitor potassium." },
  { generic: "furosemide", brand: "Lasix", drugClass: "Loop diuretic", category: "Cardiovascular", indication: "Edema, heart failure", ptceTip: "Take in morning to reduce night urination." },
  { generic: "carvedilol", brand: "Coreg", drugClass: "Beta blocker", category: "Cardiovascular", indication: "Heart failure, hypertension", ptceTip: "Non-selective beta blocker with alpha block." },
  { generic: "clopidogrel", brand: "Plavix", drugClass: "Antiplatelet", category: "Cardiovascular", indication: "CAD, stroke prevention", ptceTip: "Bleeding risk increases with NSAIDs." },
  { generic: "warfarin", brand: "Coumadin", drugClass: "Anticoagulant", category: "Cardiovascular", indication: "AFib, DVT prevention", ptceTip: "INR monitoring; many drug/food interactions." },
  { generic: "apixaban", brand: "Eliquis", drugClass: "DOAC", category: "Cardiovascular", indication: "AFib, DVT/PE", ptceTip: "No routine INR; reversal agents exist." },
  { generic: "rivaroxaban", brand: "Xarelto", drugClass: "DOAC", category: "Cardiovascular", indication: "AFib, DVT/PE", ptceTip: "Take with evening meal for 15 mg dose." },
  { generic: "spironolactone", brand: "Aldactone", drugClass: "K-sparing diuretic", category: "Cardiovascular", indication: "Heart failure, hyperaldosteronism", ptceTip: "Hyperkalemia risk." },
  { generic: "diltiazem", brand: "Cardizem", drugClass: "Calcium channel blocker", category: "Cardiovascular", indication: "Hypertension, angina, AFib rate control", ptceTip: "Non-dihydropyridine CCB." },
  { generic: "enalapril", brand: "Vasotec", drugClass: "ACE inhibitor", category: "Cardiovascular", indication: "Hypertension, heart failure", ptceTip: "ACE inhibitor class effect: cough." },
  { generic: "valsartan", brand: "Diovan", drugClass: "ARB", category: "Cardiovascular", indication: "Hypertension, heart failure", ptceTip: "Do not combine with ACE inhibitor." },
  { generic: "rosuvastatin", brand: "Crestor", drugClass: "Statin", category: "Cardiovascular", indication: "Hyperlipidemia", ptceTip: "High-potency statin." },
  { generic: "simvastatin", brand: "Zocor", drugClass: "Statin", category: "Cardiovascular", indication: "Hyperlipidemia", ptceTip: "Evening dosing; interaction with many drugs." },
  { generic: "metformin", brand: "Glucophage", drugClass: "Biguanide", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "First-line T2DM; hold before contrast dye." },
  { generic: "insulin glargine", brand: "Lantus/Basaglar", drugClass: "Long-acting insulin", category: "Diabetes", indication: "Diabetes mellitus", ptceTip: "Do not mix with other insulins in same syringe." },
  { generic: "insulin lispro", brand: "Humalog", drugClass: "Rapid-acting insulin", category: "Diabetes", indication: "Diabetes mellitus", ptceTip: "Give with meals." },
  { generic: "semaglutide", brand: "Ozempic", drugClass: "GLP-1 agonist", category: "Diabetes", indication: "Type 2 diabetes, weight management", ptceTip: "GI upset common initially." },
  { generic: "glipizide", brand: "Glucotrol", drugClass: "Sulfonylurea", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "Hypoglycemia risk." },
  { generic: "sitagliptin", brand: "Januvia", drugClass: "DPP-4 inhibitor", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "Weight-neutral oral agent." },
  { generic: "empagliflozin", brand: "Jardiance", drugClass: "SGLT2 inhibitor", category: "Diabetes", indication: "Type 2 diabetes, heart failure", ptceTip: "Genital mycotic infection risk." },
  { generic: "ibuprofen", brand: "Advil/Motrin", drugClass: "NSAID", category: "Pain & Inflammation", indication: "Pain, fever, inflammation", ptceTip: "Take with food; GI bleed risk." },
  { generic: "acetaminophen", brand: "Tylenol", drugClass: "Analgesic/antipyretic", category: "Pain & Inflammation", indication: "Pain, fever", ptceTip: "Max 3-4 g/day adults; hepatotoxicity." },
  { generic: "naproxen", brand: "Aleve/Naprosyn", drugClass: "NSAID", category: "Pain & Inflammation", indication: "Pain, inflammation", ptceTip: "Longer duration than ibuprofen." },
  { generic: "tramadol", brand: "Ultram", drugClass: "Opioid analgesic", category: "Pain & Inflammation", indication: "Moderate pain", ptceTip: "Seizure risk; serotonin syndrome with SSRIs." },
  { generic: "oxycodone", brand: "OxyContin/Roxicodone", drugClass: "Opioid (CII)", category: "Pain & Inflammation", indication: "Severe pain", ptceTip: "Schedule II; no refills." },
  { generic: "hydrocodone/APAP", brand: "Norco/Vicodin", drugClass: "Opioid combo (CII/CIII)", category: "Pain & Inflammation", indication: "Moderate-severe pain", ptceTip: "Acetaminophen limits daily tablets." },
  { generic: "gabapentin", brand: "Neurontin", drugClass: "Anticonvulsant", category: "Pain & Inflammation", indication: "Neuropathic pain, seizures", ptceTip: "Titrate slowly; sedation common." },
  { generic: "pregabalin", brand: "Lyrica", drugClass: "Anticonvulsant", category: "Pain & Inflammation", indication: "Neuropathic pain, fibromyalgia", ptceTip: "CV risk in some states scheduled." },
  { generic: "meloxicam", brand: "Mobic", drugClass: "NSAID", category: "Pain & Inflammation", indication: "OA, RA pain", ptceTip: "Once-daily NSAID." },
  { generic: "sertraline", brand: "Zoloft", drugClass: "SSRI", category: "Mental Health", indication: "Depression, anxiety", ptceTip: "Take morning if insomnia." },
  { generic: "escitalopram", brand: "Lexapro", drugClass: "SSRI", category: "Mental Health", indication: "Depression, anxiety", ptceTip: "SSRI class: serotonin syndrome risk." },
  { generic: "fluoxetine", brand: "Prozac", drugClass: "SSRI", category: "Mental Health", indication: "Depression, OCD, panic", ptceTip: "Long half-life." },
  { generic: "duloxetine", brand: "Cymbalta", drugClass: "SNRI", category: "Mental Health", indication: "Depression, neuropathic pain", ptceTip: "Do not stop abruptly." },
  { generic: "bupropion", brand: "Wellbutrin", drugClass: "NDRI", category: "Mental Health", indication: "Depression, smoking cessation", ptceTip: "Lowers seizure threshold." },
  { generic: "alprazolam", brand: "Xanax", drugClass: "Benzodiazepine (CIV)", category: "Mental Health", indication: "Anxiety, panic", ptceTip: "Short-acting benzo; dependence risk." },
  { generic: "lorazepam", brand: "Ativan", drugClass: "Benzodiazepine (CIV)", category: "Mental Health", indication: "Anxiety, seizures", ptceTip: "No active metabolites." },
  { generic: "quetiapine", brand: "Seroquel", drugClass: "Atypical antipsychotic", category: "Mental Health", indication: "Bipolar, schizophrenia", ptceTip: "Sedation and metabolic effects." },
  { generic: "aripiprazole", brand: "Abilify", drugClass: "Atypical antipsychotic", category: "Mental Health", indication: "Schizophrenia, bipolar", ptceTip: "Partial dopamine agonist." },
  { generic: "methylphenidate", brand: "Ritalin/Concerta", drugClass: "Stimulant (CII)", category: "Mental Health", indication: "ADHD", ptceTip: "Schedule II stimulant." },
  { generic: "amphetamine salts", brand: "Adderall", drugClass: "Stimulant (CII)", category: "Mental Health", indication: "ADHD", ptceTip: "Controlled substance; appetite suppression." },
  { generic: "albuterol", brand: "ProAir/Ventolin", drugClass: "SABA", category: "Respiratory", indication: "Bronchospasm, asthma", ptceTip: "Rescue inhaler; tremor common." },
  { generic: "fluticasone", brand: "Flovent", drugClass: "ICS", category: "Respiratory", indication: "Asthma maintenance", ptceTip: "Rinse mouth after use." },
  { generic: "budesonide/formoterol", brand: "Symbicort", drugClass: "ICS/LABA", category: "Respiratory", indication: "Asthma, COPD", ptceTip: "Combination inhaler." },
  { generic: "tiotropium", brand: "Spiriva", drugClass: "LAMA", category: "Respiratory", indication: "COPD", ptceTip: "Dry powder or soft mist inhaler." },
  { generic: "montelukast", brand: "Singulair", drugClass: "Leukotriene antagonist", category: "Respiratory", indication: "Asthma, allergic rhinitis", ptceTip: "Neuropsychiatric warnings." },
  { generic: "prednisone", brand: "Deltasone", drugClass: "Corticosteroid", category: "Respiratory", indication: "Inflammation, asthma exacerbation", ptceTip: "Taper if long course." },
  { generic: "amoxicillin", brand: "Amoxil", drugClass: "Penicillin", category: "Antibiotic", indication: "Bacterial infections", ptceTip: "Suspension refrigerated; allergy cross-reactivity." },
  { generic: "amoxicillin/clavulanate", brand: "Augmentin", drugClass: "Penicillin + beta-lactamase inhibitor", category: "Antibiotic", indication: "Resistant infections", ptceTip: "GI upset common." },
  { generic: "azithromycin", brand: "Zithromax/Z-Pak", drugClass: "Macrolide", category: "Antibiotic", indication: "Respiratory infections", ptceTip: "QT prolongation risk." },
  { generic: "ciprofloxacin", brand: "Cipro", drugClass: "Fluoroquinolone", category: "Antibiotic", indication: "UTI, GI infections", ptceTip: "Tendon rupture risk; avoid dairy/calcium timing." },
  { generic: "doxycycline", brand: "Vibramycin", drugClass: "Tetracycline", category: "Antibiotic", indication: "Acne, tick-borne illness", ptceTip: "Photosensitivity; avoid in pregnancy." },
  { generic: "cephalexin", brand: "Keflex", drugClass: "Cephalosporin (1st gen)", category: "Antibiotic", indication: "Skin, UTI infections", ptceTip: "Take with or without food." },
  { generic: "trimethoprim/sulfamethoxazole", brand: "Bactrim/Septra", drugClass: "Sulfonamide combo", category: "Antibiotic", indication: "UTI, MRSA (some)", ptceTip: "Sulfa allergy; hyperkalemia with trimethoprim." },
  { generic: "nitrofurantoin", brand: "Macrobid/Macrodantin", drugClass: "Antibiotic", category: "Antibiotic", indication: "UTI prophylaxis/treatment", ptceTip: "Take with food." },
  { generic: "omeprazole", brand: "Prilosec", drugClass: "PPI", category: "GI", indication: "GERD, ulcer prevention", ptceTip: "Take before breakfast." },
  { generic: "pantoprazole", brand: "Protonix", drugClass: "PPI", category: "GI", indication: "GERD, erosive esophagitis", ptceTip: "IV/oral PPI." },
  { generic: "famotidine", brand: "Pepcid", drugClass: "H2 blocker", category: "GI", indication: "GERD, heartburn", ptceTip: "Can use PRN heartburn." },
  { generic: "ondansetron", brand: "Zofran", drugClass: "5-HT3 antagonist", category: "GI", indication: "Nausea/vomiting", ptceTip: "QT prolongation at high doses." },
  { generic: "docusate", brand: "Colace", drugClass: "Stool softener", category: "GI", indication: "Constipation", ptceTip: "Stool softener not stimulant." },
  { generic: "polyethylene glycol", brand: "MiraLAX", drugClass: "Osmotic laxative", category: "GI", indication: "Constipation", ptceTip: "Mix in liquid." },
  { generic: "levothyroxine", brand: "Synthroid", drugClass: "Thyroid hormone", category: "Thyroid & Hormone", indication: "Hypothyroidism", ptceTip: "Take on empty stomach." },
  { generic: "methimazole", brand: "Tapazole", drugClass: "Antithyroid", category: "Thyroid & Hormone", indication: "Hyperthyroidism", ptceTip: "Agranulocytosis warning." },
  { generic: "estradiol", brand: "Estrace/Climara", drugClass: "Estrogen", category: "Thyroid & Hormone", indication: "Menopause symptoms", ptceTip: "Transdermal avoids first-pass." },
  { generic: "testosterone", brand: "AndroGel", drugClass: "Androgen", category: "Thyroid & Hormone", indication: "Hypogonadism", ptceTip: "Controlled transfer risk topically." },
  { generic: "hydrocortisone", brand: "Cortef", drugClass: "Corticosteroid", category: "Dermatology", indication: "Adrenal insufficiency, inflammation", ptceTip: "Short-acting steroid." },
  { generic: "triamcinolone cream", brand: "Kenalog", drugClass: "Topical corticosteroid", category: "Dermatology", indication: "Eczema, dermatitis", ptceTip: "Potency varies by vehicle." },
  { generic: "clotrimazole", brand: "Lotrimin", drugClass: "Antifungal azole", category: "Dermatology", indication: "Fungal skin infections", ptceTip: "OTC topical antifungal." },
  { generic: "finasteride", brand: "Proscar/Propecia", drugClass: "5-alpha reductase inhibitor", category: "Other", indication: "BPH, alopecia", ptceTip: "Teratogenic; handle carefully." },
  { generic: "tamsulosin", brand: "Flomax", drugClass: "Alpha blocker", category: "Other", indication: "BPH", ptceTip: "First-dose hypotension." },
  { generic: "sildenafil", brand: "Viagra", drugClass: "PDE-5 inhibitor", category: "Other", indication: "Erectile dysfunction, PAH", ptceTip: "No nitrates." },
  { generic: "allopurinol", brand: "Zyloprim", drugClass: "Xanthine oxidase inhibitor", category: "Other", indication: "Gout prevention", ptceTip: "Start low; rash risk." },
  { generic: "colchicine", brand: "Colcrys", drugClass: "Antigout", category: "Other", indication: "Gout flare", ptceTip: "GI toxicity in overdose." },
  { generic: "methotrexate", brand: "Trexall", drugClass: "DMARD", category: "Other", indication: "RA, psoriasis", ptceTip: "Folic acid often prescribed." },
  { generic: "cyclobenzaprine", brand: "Flexeril", drugClass: "Muscle relaxant", category: "Other", indication: "Muscle spasm", ptceTip: "Sedating." },
  { generic: "zolpidem", brand: "Ambien", drugClass: "Sedative-hypnotic (CIV)", category: "Other", indication: "Insomnia", ptceTip: "Short-term use; complex sleep behaviors." },
  { generic: "diphenhydramine", brand: "Benadryl", drugClass: "Antihistamine 1st gen", category: "Other", indication: "Allergies, sleep aid", ptceTip: "Anticholinergic; sedation." },
  { generic: "cetirizine", brand: "Zyrtec", drugClass: "Antihistamine 2nd gen", category: "Other", indication: "Allergic rhinitis, urticaria", ptceTip: "Less sedating than diphenhydramine." },
  { generic: "loratadine", brand: "Claritin", drugClass: "Antihistamine 2nd gen", category: "Other", indication: "Allergic rhinitis", ptceTip: "Non-sedating antihistamine." },
  { generic: "fluticasone nasal", brand: "Flonase", drugClass: "Intranasal corticosteroid", category: "Other", indication: "Allergic rhinitis", ptceTip: "Prime spray initially." },
  { generic: "epinephrine", brand: "EpiPen", drugClass: "Sympathomimetic", category: "Other", indication: "Anaphylaxis", ptceTip: "IM anterolateral thigh." },
  { generic: "naloxone", brand: "Narcan", drugClass: "Opioid antagonist", category: "Other", indication: "Opioid overdose", ptceTip: "May need repeat doses." },
  { generic: "methylprednisolone", brand: "Medrol Dosepak", drugClass: "Corticosteroid", category: "Other", indication: "Inflammation", ptceTip: "Taper packs common." },
  { generic: "digoxin", brand: "Lanoxin", drugClass: "Cardiac glycoside", category: "Cardiovascular", indication: "Heart failure, AFib", ptceTip: "Narrow therapeutic index." },
  { generic: "isosorbide mononitrate", brand: "Imdur", drugClass: "Nitrate", category: "Cardiovascular", indication: "Angina prevention", ptceTip: "Nitrate-free interval needed." },
  { generic: "nitroglycerin", brand: "Nitrostat", drugClass: "Nitrate", category: "Cardiovascular", indication: "Acute angina", ptceTip: "SL tablet; light-sensitive." },
  { generic: "amiodarone", brand: "Pacerone", drugClass: "Antiarrhythmic", category: "Cardiovascular", indication: "Ventricular arrhythmias, AFib", ptceTip: "Pulmonary/thyroid toxicity." },
  { generic: "prasugrel", brand: "Effient", drugClass: "Antiplatelet", category: "Cardiovascular", indication: "ACS with PCI", ptceTip: "More potent than clopidogrel." },
  { generic: "ticagrelor", brand: "Brilinta", drugClass: "Antiplatelet", category: "Cardiovascular", indication: "ACS", ptceTip: "Dyspnea side effect." },
  { generic: "sacubitril/valsartan", brand: "Entresto", drugClass: "ARNI", category: "Cardiovascular", indication: "HFrEF", ptceTip: "Do not use with ACE inhibitor." },
  { generic: "ranolazine", brand: "Ranexa", drugClass: "Antianginal", category: "Cardiovascular", indication: "Chronic angina", ptceTip: "QT prolongation." },
  { generic: "ezetimibe", brand: "Zetia", drugClass: "Cholesterol absorption inhibitor", category: "Cardiovascular", indication: "Hyperlipidemia", ptceTip: "Often combined with statin." },
  { generic: "fenofibrate", brand: "Tricor", drugClass: "Fibrate", category: "Cardiovascular", indication: "Hypertriglyceridemia", ptceTip: "Myopathy with statins." },
  { generic: "pravastatin", brand: "Pravachol", drugClass: "Statin", category: "Cardiovascular", indication: "Hyperlipidemia", ptceTip: "Fewer CYP interactions." },
  { generic: "propranolol", brand: "Inderal", drugClass: "Beta blocker", category: "Cardiovascular", indication: "Hypertension, migraine prophylaxis", ptceTip: "Non-selective beta blocker." },
  { generic: "atenolol", brand: "Tenormin", drugClass: "Beta blocker", category: "Cardiovascular", indication: "Hypertension, angina", ptceTip: "Beta-1 selective." },
  { generic: "bisoprolol", brand: "Zebeta", drugClass: "Beta blocker", category: "Cardiovascular", indication: "Hypertension, heart failure", ptceTip: "Beta-1 selective." },
  { generic: "verapamil", brand: "Calan", drugClass: "Calcium channel blocker", category: "Cardiovascular", indication: "Hypertension, AFib", ptceTip: "Constipation common." },
  { generic: "hydralazine", brand: "Apresoline", drugClass: "Vasodilator", category: "Cardiovascular", indication: "Hypertension", ptceTip: "Reflex tachycardia." },
  { generic: "clonidine", brand: "Catapres", drugClass: "Alpha-2 agonist", category: "Cardiovascular", indication: "Hypertension, ADHD", ptceTip: "Rebound hypertension if stopped." },
  { generic: "insulin aspart", brand: "NovoLog", drugClass: "Rapid insulin", category: "Diabetes", indication: "Diabetes", ptceTip: "Rapid acting mealtime insulin." },
  { generic: "insulin detemir", brand: "Levemir", drugClass: "Long-acting insulin", category: "Diabetes", indication: "Diabetes", ptceTip: "May need twice daily." },
  { generic: "insulin degludec", brand: "Tresiba", drugClass: "Ultra long insulin", category: "Diabetes", indication: "Diabetes", ptceTip: "Very long duration." },
  { generic: "glyburide", brand: "DiaBeta", drugClass: "Sulfonylurea", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "Higher hypoglycemia risk in elderly." },
  { generic: "pioglitazone", brand: "Actos", drugClass: "Thiazolidinedione", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "Edema and heart failure risk." },
  { generic: "canagliflozin", brand: "Invokana", drugClass: "SGLT2 inhibitor", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "Volume depletion risk." },
  { generic: "liraglutide", brand: "Victoza", drugClass: "GLP-1 agonist", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "Injectable GLP-1." },
  { generic: "dulaglutide", brand: "Trulicity", drugClass: "GLP-1 agonist", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "Weekly injection." },
  { generic: "metoclopramide", brand: "Reglan", drugClass: "Prokinetic/antiemetic", category: "GI", indication: "Gastroparesis, nausea", ptceTip: "Extrapyramidal effects." },
  { generic: "sucralfate", brand: "Carafate", drugClass: "Mucosal protectant", category: "GI", indication: "Ulcer", ptceTip: "Separate from other meds." },
  { generic: "loperamide", brand: "Imodium", drugClass: "Antidiarrheal", category: "GI", indication: "Diarrhea", ptceTip: "OTC antidiarrheal." },
  { generic: "mesalamine", brand: "Asacol/Lialda", drugClass: "5-ASA", category: "GI", indication: "Ulcerative colitis", ptceTip: "Do not crush delayed-release." },
  { generic: "lansoprazole", brand: "Prevacid", drugClass: "PPI", category: "GI", indication: "GERD", ptceTip: "PPI before meals." },
  { generic: "esomeprazole", brand: "Nexium", drugClass: "PPI", category: "GI", indication: "GERD", ptceTip: "S-isomer of omeprazole." },
  { generic: "promethazine", brand: "Phenergan", drugClass: "Antihistamine/antiemetic", category: "GI", indication: "Nausea, allergies", ptceTip: "Sedation; tissue injury if IV extravasation." },
  { generic: "ceftriaxone", brand: "Rocephin", drugClass: "Cephalosporin (3rd gen)", category: "Antibiotic", indication: "Serious infections", ptceTip: "IM/IV; biliary sludging in neonates." },
  { generic: "levofloxacin", brand: "Levaquin", drugClass: "Fluoroquinolone", category: "Antibiotic", indication: "Respiratory, UTI", ptceTip: "Tendon and CNS effects." },
  { generic: "metronidazole", brand: "Flagyl", drugClass: "Nitroimidazole", category: "Antibiotic", indication: "Anaerobic infections, C. diff", ptceTip: "No alcohol (disulfiram-like)." },
  { generic: "clindamycin", brand: "Cleocin", drugClass: "Lincosamide", category: "Antibiotic", indication: "Skin, anaerobic infections", ptceTip: "C. diff risk." },
  { generic: "vancomycin", brand: "Vancocin", drugClass: "Glycopeptide", category: "Antibiotic", indication: "MRSA, C. diff (oral)", ptceTip: "Trough levels for IV." },
  { generic: "linezolid", brand: "Zyvox", drugClass: "Oxazolidinone", category: "Antibiotic", indication: "MRSA, VRE", ptceTip: "Serotonin syndrome with SSRIs." },
  { generic: "daptomycin", brand: "Cubicin", drugClass: "Lipopeptide", category: "Antibiotic", indication: "MRSA bacteremia", ptceTip: "CK monitoring." },
  { generic: "rifampin", brand: "Rifadin", drugClass: "Antitubercular", category: "Antibiotic", indication: "TB, prophylaxis", ptceTip: "Orange body fluids." },
  { generic: "isoniazid", brand: "INH", drugClass: "Antitubercular", category: "Antibiotic", indication: "Tuberculosis", ptceTip: "Peripheral neuropathy; B6." },
  { generic: "acyclovir", brand: "Zovirax", drugClass: "Antiviral", category: "Antibiotic", indication: "Herpes infections", ptceTip: "Renal dosing." },
  { generic: "valacyclovir", brand: "Valtrex", drugClass: "Antiviral prodrug", category: "Antibiotic", indication: "Herpes, shingles", ptceTip: "Prodrug of acyclovir." },
  { generic: "oseltamivir", brand: "Tamiflu", drugClass: "Neuraminidase inhibitor", category: "Antibiotic", indication: "Influenza", ptceTip: "Start within 48 hours." },
  { generic: "nirmatrelvir/ritonavir", brand: "Paxlovid", drugClass: "Antiviral combo", category: "Antibiotic", indication: "COVID-19", ptceTip: "Many drug interactions via ritonavir." },
  { generic: "paroxetine", brand: "Paxil", drugClass: "SSRI", category: "Mental Health", indication: "Depression, anxiety", ptceTip: "Anticholinergic among SSRIs." },
  { generic: "venlafaxine", brand: "Effexor", drugClass: "SNRI", category: "Mental Health", indication: "Depression, anxiety", ptceTip: "Hypertension at high doses." },
  { generic: "mirtazapine", brand: "Remeron", drugClass: "Tetracyclic antidepressant", category: "Mental Health", indication: "Depression", ptceTip: "Increases appetite." },
  { generic: "trazodone", brand: "Desyrel", drugClass: "SARI", category: "Mental Health", indication: "Depression, insomnia", ptceTip: "Sedation common." },
  { generic: "lithium", brand: "Lithobid", drugClass: "Mood stabilizer", category: "Mental Health", indication: "Bipolar disorder", ptceTip: "Narrow therapeutic index; hydration." },
  { generic: "lamotrigine", brand: "Lamictal", drugClass: "Anticonvulsant", category: "Mental Health", indication: "Bipolar, seizures", ptceTip: "SJS risk; slow titration." },
  { generic: "olanzapine", brand: "Zyprexa", drugClass: "Atypical antipsychotic", category: "Mental Health", indication: "Schizophrenia, bipolar", ptceTip: "Metabolic weight gain." },
  { generic: "risperidone", brand: "Risperdal", drugClass: "Atypical antipsychotic", category: "Mental Health", indication: "Schizophrenia, bipolar", ptceTip: "EPS and prolactin effects." },
  { generic: "haloperidol", brand: "Haldol", drugClass: "Typical antipsychotic", category: "Mental Health", indication: "Psychosis, agitation", ptceTip: "EPS and QT risk." },
  { generic: "buspirone", brand: "Buspar", drugClass: "Anxiolytic", category: "Mental Health", indication: "Anxiety", ptceTip: "Not a benzo; delayed onset." },
  { generic: "atomoxetine", brand: "Strattera", drugClass: "NRI", category: "Mental Health", indication: "ADHD", ptceTip: "Non-stimulant ADHD option." },
  { generic: "guanfacine ER", brand: "Intuniv", drugClass: "Alpha-2 agonist", category: "Mental Health", indication: "ADHD", ptceTip: "Sedation and hypotension." },
  { generic: "formoterol", brand: "Foradil", drugClass: "LABA", category: "Respiratory", indication: "Asthma, COPD", ptceTip: "Not for acute rescue." },
  { generic: "salmeterol", brand: "Serevent", drugClass: "LABA", category: "Respiratory", indication: "Asthma, COPD", ptceTip: "Always with ICS in asthma." },
  { generic: "ipratropium", brand: "Atrovent", drugClass: "SAMA", category: "Respiratory", indication: "COPD, bronchospasm", ptceTip: "Anticholinergic inhaler." },
  { generic: "roflumilast", brand: "Daliresp", drugClass: "PDE-4 inhibitor", category: "Respiratory", indication: "COPD", ptceTip: "Oral COPD maintenance." },
  { generic: "benzonatate", brand: "Tessalon", drugClass: "Antitussive", category: "Respiratory", indication: "Cough", ptceTip: "Chewing causes numbness/serious risk." },
  { generic: "guaifenesin", brand: "Mucinex", drugClass: "Expectorant", category: "Respiratory", indication: "Cough with mucus", ptceTip: "Hydration helps efficacy." },
  { generic: "theophylline", brand: "Theo-24", drugClass: "Methylxanthine", category: "Respiratory", indication: "Asthma, COPD", ptceTip: "Narrow therapeutic index." },
  { generic: "sumatriptan", brand: "Imitrex", drugClass: "Triptan", category: "Other", indication: "Migraine", ptceTip: "Do not use in uncontrolled HTN." },
  { generic: "rizatriptan", brand: "Maxalt", drugClass: "Triptan", category: "Other", indication: "Migraine", ptceTip: "Serotonin syndrome with SSRIs." },
  { generic: "topiramate", brand: "Topamax", drugClass: "Anticonvulsant", category: "Other", indication: "Migraine prophylaxis, seizures", ptceTip: "Cognitive slowing, kidney stones." },
  { generic: "levetiracetam", brand: "Keppra", drugClass: "Anticonvulsant", category: "Other", indication: "Seizures", ptceTip: "Behavioral side effects." },
  { generic: "phenytoin", brand: "Dilantin", drugClass: "Anticonvulsant", category: "Other", indication: "Seizures", ptceTip: "Zero-order kinetics at high levels." },
  { generic: "carbamazepine", brand: "Tegretol", drugClass: "Anticonvulsant", category: "Other", indication: "Seizures, trigeminal neuralgia", ptceTip: "SJS in HLA-B*1502." },
  { generic: "levocetirizine", brand: "Xyzal", drugClass: "Antihistamine", category: "Other", indication: "Allergic rhinitis", ptceTip: "Active enantiomer of cetirizine." },
  { generic: "fexofenadine", brand: "Allegra", drugClass: "Antihistamine", category: "Other", indication: "Allergic rhinitis", ptceTip: "Avoid fruit juice near dose." },
  { generic: "pseudoephedrine", brand: "Sudafed", drugClass: "Decongestant", category: "Other", indication: "Nasal congestion", ptceTip: "Behind counter; BP elevation." },
  { generic: "phenylephrine", brand: "Sudafed PE", drugClass: "Decongestant", category: "Other", indication: "Nasal congestion", ptceTip: "Less effective orally for some." },
  { generic: "hydroxyzine", brand: "Vistaril/Atarax", drugClass: "Antihistamine", category: "Other", indication: "Anxiety, pruritus", ptceTip: "Sedating antihistamine." },
  { generic: "ketoconazole", brand: "Nizoral", drugClass: "Antifungal", category: "Dermatology", indication: "Fungal infections", ptceTip: "Systemic hepatotoxicity." },
  { generic: "terbinafine", brand: "Lamisil", drugClass: "Antifungal", category: "Dermatology", indication: "Onychomycosis", ptceTip: "Monitor LFTs oral." },
  { generic: "mupirocin", brand: "Bactroban", drugClass: "Topical antibiotic", category: "Dermatology", indication: "Impetigo, nasal MRSA", ptceTip: "Intranasal for decolonization." },
  { generic: "tretinoin", brand: "Retin-A", drugClass: "Retinoid", category: "Dermatology", indication: "Acne", ptceTip: "Photosensitivity." },
  { generic: "benzoyl peroxide", brand: "Benzac", drugClass: "Antiacne topical", category: "Dermatology", indication: "Acne", ptceTip: "Bleaches fabric." },
  { generic: "permethrin", brand: "Nix/Elimite", drugClass: "Scabicide/pediculicide", category: "Dermatology", indication: "Scabies, lice", ptceTip: "Topical application." },
  { generic: "silver sulfadiazine", brand: "Silvadene", drugClass: "Topical antimicrobial", category: "Dermatology", indication: "Burn wound", ptceTip: "Sulfa-based cream." },
  { generic: "calcipotriene", brand: "Dovonex", drugClass: "Vitamin D analog", category: "Dermatology", indication: "Psoriasis", ptceTip: "Hypercalcemia if overused." },
  { generic: "adalimumab", brand: "Humira", drugClass: "TNF inhibitor", category: "Other", indication: "RA, psoriasis, IBD", ptceTip: "Infection risk biologic." },
  { generic: "etanercept", brand: "Enbrel", drugClass: "TNF inhibitor", category: "Other", indication: "RA, psoriasis", ptceTip: "Refrigerate." },
  { generic: "infliximab", brand: "Remicade", drugClass: "TNF inhibitor", category: "Other", indication: "IBD, RA", ptceTip: "IV infusion biologic." },
  { generic: "secukinumab", brand: "Cosentyx", drugClass: "IL-17 inhibitor", category: "Other", indication: "Psoriasis", ptceTip: "Biologic injection." },
  { generic: "apixaban reversal", brand: "Andexxa", drugClass: "Reversal agent", category: "Other", indication: "Apixaban reversal", ptceTip: "Specialty reversal." },
  { generic: "vitamin D3", brand: "Cholecalciferol", drugClass: "Vitamin", category: "Other", indication: "Vitamin D deficiency", ptceTip: "Fat-soluble vitamin." },
  { generic: "calcium carbonate", brand: "Tums", drugClass: "Antacid/supplement", category: "Other", indication: "Calcium supplementation, heartburn", ptceTip: "Take with food; constipation." },
  { generic: "ferrous sulfate", brand: "Feosol", drugClass: "Iron supplement", category: "Other", indication: "Iron deficiency anemia", ptceTip: "Black stools; take with vitamin C." },
  { generic: "potassium chloride", brand: "K-Dur", drugClass: "Electrolyte", category: "Other", indication: "Hypokalemia", ptceTip: "Do not crush ER tabs." },
  { generic: "magnesium oxide", brand: "Mag-Ox", drugClass: "Magnesium supplement", category: "Other", indication: "Hypomagnesemia", ptceTip: "Laxative effect." },
  { generic: "cyanocobalamin", brand: "Vitamin B12", drugClass: "Vitamin", category: "Other", indication: "B12 deficiency", ptceTip: "IM or oral depending on cause." },
  { generic: "folic acid", brand: "Folvite", drugClass: "Vitamin", category: "Other", indication: "Folate deficiency", ptceTip: "Masks B12 deficiency." },
  { generic: "multivitamin", brand: "Centrum", drugClass: "Vitamin combo", category: "Other", indication: "Nutritional supplementation", ptceTip: "OTC supplement." },
  { generic: "fish oil", brand: "Omega-3", drugClass: "Supplement", category: "Other", indication: "Hypertriglyceridemia support", ptceTip: "Bleeding risk high doses." },
  { generic: "cholecalciferol", brand: "Vitamin D", drugClass: "Vitamin", category: "Other", indication: "Vitamin D deficiency", ptceTip: "D2 vs D3 distinctions." },
  { generic: "prenatal vitamin", brand: "Prenatal", drugClass: "Vitamin combo", category: "Other", indication: "Pregnancy nutrition", ptceTip: "Folic acid essential." },
  { generic: "aspirin", brand: "Bayer", drugClass: "Antiplatelet/NSAID", category: "Cardiovascular", indication: "CAD prevention, pain", ptceTip: "Low-dose for cardioprotection." },
  { generic: "nitrofurantoin macro", brand: "Macrobid", drugClass: "Antibiotic", category: "Antibiotic", indication: "UTI", ptceTip: "Macro vs Macrodantin dosing." },
  { generic: "hydroxychloroquine", brand: "Plaquenil", drugClass: "Antimalarial/DMARD", category: "Other", indication: "RA, lupus", ptceTip: "Retinal toxicity screening." },
  { generic: "sulfasalazine", brand: "Azulfidine", drugClass: "DMARD", category: "Other", indication: "RA, UC", ptceTip: "Sulfa component." },
  { generic: "baclofen", brand: "Lioresal", drugClass: "Muscle relaxant", category: "Other", indication: "Spasticity", ptceTip: "Do not stop abruptly." },
  { generic: "tizanidine", brand: "Zanaflex", drugClass: "Muscle relaxant", category: "Other", indication: "Muscle spasm", ptceTip: "Hypotension and sedation." },
  { generic: "oxybutynin", brand: "Ditropan", drugClass: "Anticholinergic", category: "Other", indication: "Overactive bladder", ptceTip: "Dry mouth common." },
  { generic: "tolterodine", brand: "Detrol", drugClass: "Anticholinergic", category: "Other", indication: "Overactive bladder", ptceTip: "Anticholinergic burden." },
  { generic: "mirabegron", brand: "Myrbetriq", drugClass: "Beta-3 agonist", category: "Other", indication: "Overactive bladder", ptceTip: "May increase BP." },
  { generic: "solifenacin", brand: "Vesicare", drugClass: "Anticholinergic", category: "Other", indication: "Overactive bladder", ptceTip: "Once daily anticholinergic." },
  { generic: "finasteride/tamsulosin", brand: "Jalyn", drugClass: "BPH combo", category: "Other", indication: "BPH", ptceTip: "Combo for prostate." },
  { generic: "desmopressin", brand: "DDAVP", drugClass: "Antidiuretic hormone analog", category: "Other", indication: "Diabetes insipidus, nocturnal enuresis", ptceTip: "Hyponatremia risk." },
  { generic: "levonorgestrel", brand: "Plan B", drugClass: "Emergency contraceptive", category: "Other", indication: "Emergency contraception", ptceTip: "OTC timing sensitive." },
  { generic: "ethinyl estradiol/norgestimate", brand: "Ortho Tri-Cyclen", drugClass: "Combined OCP", category: "Other", indication: "Contraception", ptceTip: "Take same time daily." },
  { generic: "norethindrone", brand: "Micronor", drugClass: "Progestin-only pill", category: "Other", indication: "Contraception", ptceTip: "POP strict timing." },
  { generic: "medroxyprogesterone", brand: "Depo-Provera", drugClass: "Progestin injection", category: "Other", indication: "Contraception", ptceTip: "Q12 weeks injection." },
  { generic: "clomiphene", brand: "Clomid", drugClass: "Ovulation inducer", category: "Other", indication: "Infertility", ptceTip: "Ovulation monitoring." },
  { generic: "letrozole", brand: "Femara", drugClass: "Aromatase inhibitor", category: "Other", indication: "Breast cancer", ptceTip: "AI for hormone-positive breast cancer." },
  { generic: "tamoxifen", brand: "Nolvadex", drugClass: "SERM", category: "Other", indication: "Breast cancer prevention/treatment", ptceTip: "Endometrial cancer risk." },
  { generic: "anastrozole", brand: "Arimidex", drugClass: "Aromatase inhibitor", category: "Other", indication: "Breast cancer", ptceTip: "Bone loss monitoring." },
  { generic: "pantoprazole IV", brand: "Protonix IV", drugClass: "PPI", category: "GI", indication: "GI bleed prophylaxis", ptceTip: "IV PPI in hospital." },
  { generic: "heparin", brand: "Heparin", drugClass: "Anticoagulant", category: "Cardiovascular", indication: "DVT/PE treatment", ptceTip: "aPTT monitoring." },
  { generic: "enoxaparin", brand: "Lovenox", drugClass: "LMWH", category: "Cardiovascular", indication: "DVT/PE prophylaxis and treatment", ptceTip: "Renal dose adjustment." },
  { generic: "fondaparinux", brand: "Arixtra", drugClass: "Factor Xa inhibitor", category: "Cardiovascular", indication: "DVT/PE", ptceTip: "Synthetic pentasaccharide." },
  { generic: "dabigatran", brand: "Pradaxa", drugClass: "DOAC", category: "Cardiovascular", indication: "AFib, DVT/PE", ptceTip: "Direct thrombin inhibitor." },
  { generic: "edoxaban", brand: "Savaysa", drugClass: "DOAC", category: "Cardiovascular", indication: "AFib, DVT/PE", ptceTip: "Factor Xa inhibitor." },
  { generic: "amiodarone IV", brand: "Nexterone", drugClass: "Antiarrhythmic", category: "Cardiovascular", indication: "Ventricular arrhythmias", ptceTip: "IV loading protocols." },
  { generic: "adenosine", brand: "Adenocard", drugClass: "Antiarrhythmic", category: "Cardiovascular", indication: "SVT", ptceTip: "Very short half-life IV push." },
  { generic: "magnesium sulfate", brand: "MgSO4", drugClass: "Electrolyte", category: "Other", indication: "Eclampsia, hypomagnesemia", ptceTip: "IV cardiac monitoring." },
  { generic: "potassium phosphate", brand: "K-Phos", drugClass: "Electrolyte", category: "Other", indication: "Hypophosphatemia", ptceTip: "IV electrolyte replacement." },
  { generic: "sodium bicarbonate", brand: "Baking soda Rx", drugClass: "Alkalinizing agent", category: "Other", indication: "Metabolic acidosis", ptceTip: "IV alkalinization." },
  { generic: "activated charcoal", brand: "Actidose", drugClass: "Adsorbent", category: "Other", indication: "Poisoning", ptceTip: "Early after ingestion." },
  { generic: "glucagon", brand: "Glucagon", drugClass: "Antihypoglycemic", category: "Diabetes", indication: "Severe hypoglycemia", ptceTip: "IM/IN for unconscious hypoglycemia." },
  { generic: "dextrose 50%", brand: "D50", drugClass: "Carbohydrate", category: "Diabetes", indication: "Hypoglycemia", ptceTip: "IV push hypoglycemia." },
  { generic: "insulin regular", brand: "Humulin R", drugClass: "Short-acting insulin", category: "Diabetes", indication: "Diabetes, IV insulin", ptceTip: "Only insulin for IV." },
  { generic: "liraglutide weight", brand: "Saxenda", drugClass: "GLP-1 agonist", category: "Diabetes", indication: "Chronic weight management", ptceTip: "Higher dose than Victoza." },
  { generic: "phentermine", brand: "Adipex-P", drugClass: "Anorectic (CIV)", category: "Other", indication: "Short-term weight loss", ptceTip: "Controlled stimulant." },
  { generic: "orlistat", brand: "Alli/Xenical", drugClass: "Lipase inhibitor", category: "Other", indication: "Weight management", ptceTip: "GI fat malabsorption effects." },
  { generic: "naltrexone/bupropion", brand: "Contrave", drugClass: "Weight loss combo", category: "Other", indication: "Chronic weight management", ptceTip: "Combo CNS agents." },
  { generic: "tirzepatide", brand: "Mounjaro/Zepbound", drugClass: "GIP/GLP-1 agonist", category: "Diabetes", indication: "T2DM, obesity", ptceTip: "Dual incretin agonist." },
  { generic: "insulin NPH", brand: "Humulin N", drugClass: "Intermediate insulin", category: "Diabetes", indication: "Diabetes", ptceTip: "Cloudy insulin; roll gently." },
  { generic: "insulin 70/30", brand: "Humulin 70/30", drugClass: "Premixed insulin", category: "Diabetes", indication: "Diabetes", ptceTip: "Premixed NPH/regular." },
  { generic: "repaglinide", brand: "Prandin", drugClass: "Meglitinide", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "Rapid glucose lowering mealtime." },
  { generic: "acarbose", brand: "Precose", drugClass: "Alpha-glucosidase inhibitor", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "GI flatulence common." },
  { generic: "bromocriptine quick release", brand: "Cycloset", drugClass: "Dopamine agonist", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "Morning dose within 2 hours waking." },
  { generic: "colesevelam", brand: "Welchol", drugClass: "Bile acid sequestrant", category: "Diabetes", indication: "T2DM, hyperlipidemia", ptceTip: "Separate from other meds." },
  { generic: "pramlintide", brand: "Symlin", drugClass: "Amylin analog", category: "Diabetes", indication: "Diabetes adjunct", ptceTip: "Injectable with insulin." },
  { generic: "exenatide", brand: "Byetta", drugClass: "GLP-1 agonist", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "Twice daily GLP-1." },
  { generic: "insulin glulisine", brand: "Apidra", drugClass: "Rapid insulin", category: "Diabetes", indication: "Diabetes", ptceTip: "Rapid acting analog." },
  { generic: "insulin degludec/asp", brand: "Ryzodeg", drugClass: "Insulin combo", category: "Diabetes", indication: "Diabetes", ptceTip: "Basal-bolus combo." },
  { generic: "dapagliflozin", brand: "Farxiga", drugClass: "SGLT2 inhibitor", category: "Diabetes", indication: "T2DM, heart failure, CKD", ptceTip: "Volume and UTI risk." },
  { generic: "ertugliflozin", brand: "Steglatro", drugClass: "SGLT2 inhibitor", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "SGLT2 class effects." },
  { generic: "linagliptin", brand: "Tradjenta", drugClass: "DPP-4 inhibitor", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "Renal dosing minimal." },
  { generic: "saxagliptin", brand: "Onglyza", drugClass: "DPP-4 inhibitor", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "Heart failure caution." },
  { generic: "alogliptin", brand: "Nesina", drugClass: "DPP-4 inhibitor", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "DPP-4 class." },
  { generic: "glimepiride", brand: "Amaryl", drugClass: "Sulfonylurea", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "Once daily sulfonylurea." },
  { generic: "chlorpropamide", brand: "Diabinese", drugClass: "Sulfonylurea", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "Long-acting sulfonylurea." },
  { generic: "tolbutamide", brand: "Orinase", drugClass: "Sulfonylurea", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "Older sulfonylurea." },
  { generic: "nateglinide", brand: "Starlix", drugClass: "Meglitinide", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "Short-acting prandial agent." },
  { generic: "rosiglitazone", brand: "Avandia", drugClass: "Thiazolidinedione", category: "Diabetes", indication: "Type 2 diabetes", ptceTip: "HF contraindication." },
  { generic: "bromfenac", brand: "Bromday", drugClass: "NSAID ophthalmic", category: "Other", indication: "Post-op inflammation", ptceTip: "Ophthalmic NSAID." },
  { generic: "timolol ophthalmic", brand: "Timoptic", drugClass: "Beta blocker ophthalmic", category: "Other", indication: "Glaucoma", ptceTip: "Systemic beta blockade possible." },
  { generic: "latanoprost", brand: "Xalatan", drugClass: "Prostaglandin analog", category: "Other", indication: "Glaucoma", ptceTip: "Eyelash growth side effect." },
  { generic: "brimonidine", brand: "Alphagan", drugClass: "Alpha-2 agonist ophthalmic", category: "Other", indication: "Glaucoma", ptceTip: "Ocular redness rebound." },
  { generic: "dorzolamide", brand: "Trusopt", drugClass: "Carbonic anhydrase inhibitor ophthalmic", category: "Other", indication: "Glaucoma", ptceTip: "Sulfa allergy caution." },
  { generic: "travoprost", brand: "Travatan", drugClass: "Prostaglandin analog", category: "Other", indication: "Glaucoma", ptceTip: "Evening dosing." },
  { generic: "bimatoprost", brand: "Lumigan", drugClass: "Prostaglandin analog", category: "Other", indication: "Glaucoma", ptceTip: "Iris pigmentation change." },
];

const withIds: TopDrug[] = DRUGS.slice(0, 200).map((drug, index) => ({
  ...drug,
  id: `drug-${String(index + 1).padStart(3, "0")}`,
}));

const outputPath = path.join(process.cwd(), "data", "top200-drugs.json");
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, JSON.stringify(withIds, null, 2));
console.log(`Wrote ${withIds.length} drugs to ${outputPath}`);
